name: RPC proxy CI

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: build and deploy proxy to SFO3
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SSH_PROX_HOST_TEST_SFO3 }}
        username: ${{ vars.SSH_USER_TEST }}
        key: ${{ secrets.SSH_PROX_ED25519KEY_TEST }}
        port: ${{ vars.SSH_PORT_TEST }}
        command_timeout: 60m
        script: |
          cd ~/rpc-prox
          git pull origin dev
          yarn
          ~/restart_prox.sh